apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
        - name: php-fpm
          image: ${APP_IMAGE}
          stdin: true
          tty: true
          ports:
            - containerPort: 9000
          # command: [./src/bin/test]
          # livenessProbe:
          #   exec:
          #     command: ["/usr/local/bin/docker-php-fpm.sh", "15"]
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          #   failureThreshold: 2
          resources:
            limits:
              # cpu: "200m" #https://www.youtube.com/watch?v=KCFFZ_qfKXk
              memory: "512Mi"
            requests:
              # cpu: "500m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: mysql-secrets
        - name: nginx
          image: ${NGINX_IMAGE}
          envFrom:
            - configMapRef:
                name: nginx-config
          stdin: true
          tty: true
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command: ["/usr/local/bin/docker-nginx.sh"]
          resources:
            limits:
              # cpu: "200m" #https://www.youtube.com/watch?v=KCFFZ_qfKXk
              memory: "512Mi"
            requests:
              # cpu: "500m"
              memory: "256Mi"
