apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: production
namePrefix: prod-

configMapGenerator:
  - name: ingress-nginx-php
  - name: app-config
    literals:
      - 'APP_MODE="0"'
      - "APP_IMAGE_VERSION=1.0.1"
      - "NGINX_IMAGE_VERSION=1.0.1"
  - name: nginx-config
    literals:
      - "NGINX_SERVER_NAME=production.learning.daddyy"
      - "NGINX_ACCESS_LOG=/proc/1/fd/2"
      - "NGINX_ERROR_LOG=/proc/1/fd/2"
      - "PHP_SERVICE=127.0.0.1"
      - "DIR_WWW=/var/www/html/www"
      - 'NGINX_PORT="80"'
      - 'PHP_PORT="9000"'
secretGenerator:
  - name: mysql-secrets
    literals:
      - "MYSQL_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=test"
      - "MYSQL_PORT=3306"
      - "MYSQL_HOST=192.168.49.1"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
    type: Opaque
replicas:
  - name: deployment-nginx-php
    count: 2
